table 'Salary Slabs'
	lineageTag: 7a48289a-b159-41da-9d92-aa54eece2e7d

	column SlabsID
		dataType: int64
		formatString: 0
		lineageTag: c9e78c38-fd33-4350-a9a7-112c19afbf28
		summarizeBy: none
		sourceColumn: SlabsID

		annotation SummarizationSetBy = Automatic

	column Start
		dataType: int64
		formatString: 0
		lineageTag: 4e573b9a-f0f3-4b67-a6fa-0978b1e69ed8
		summarizeBy: sum
		sourceColumn: Start

		annotation SummarizationSetBy = Automatic

	column End
		dataType: string
		lineageTag: 2a199771-004d-4b9b-acae-1a2e5cbcaae6
		summarizeBy: none
		sourceColumn: End

		annotation SummarizationSetBy = Automatic

	column Slabs
		dataType: string
		lineageTag: 8a7e89fa-8e4c-4548-9e34-6aeceb4ca5cc
		summarizeBy: none
		sourceColumn: Slabs
		sortByColumn: SlabsID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Salary Slabs' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Rco9CsAgDAXgu2RWiKkV155DXArO3Xr+5rcGAnl53xhQIAHyNuSROzdMcs40gLwQ1B1oXXLf6vBWVEFn3Rjn39XoFZJDEyxpyzOAyhqSXNYtWwCR1/28yx4KLc/5AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SlabsID = _t, Start = _t, End = _t, Slabs = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"SlabsID", Int64.Type}, {"Start", Int64.Type}, {"End", type text}, {"Slabs", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

