table 'Tenure Slabs'
	lineageTag: c1dd6e8c-2585-4051-963d-1c1381c5f45c

	column TenureID
		dataType: int64
		formatString: 0
		lineageTag: 4a87f6be-71de-4f6e-9661-2be71ee92943
		summarizeBy: none
		sourceColumn: TenureID

		annotation SummarizationSetBy = Automatic

	column 'Tenure Slabs'
		dataType: string
		lineageTag: 273bb885-8611-484c-97a2-8a8fa24d1bd8
		summarizeBy: none
		sourceColumn: Tenure Slabs
		sortByColumn: TenureID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Tenure Slabs' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("JckxEoAwCAXRu/w6zEAI9p4DaXSsrcz5g9jtm3WHoOF4mfUSRHP0dCet1uxBVj2yjYQLlhAm+df2yWg/n3kjYgE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [TenureID = _t, #"Tenure Slabs" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"TenureID", Int64.Type}, {"Tenure Slabs", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

